sudo: false
language: python
cache: pip
python:
  - "3.5"
  - "3.6"

env:
  - SLURPER_PROJECT=./tests

services:
  - postgresql
before_script:
  - psql -c 'create database slurpertest;' -U postgres

install: pip install tox-travis codecov
script: tox
after_success:
  - if [[ "$TOXENV" -eq "py36" ]]; then coverage xml; codecov; fi
